application: datastore-test-site
version: 1
runtime: go
api_version: go1

handlers:
- url: /user/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin
  auth_fail_action: unauthorized

- url: /.*
  script: _go_app